from odoo import fields, models


class Lead(models.Model):
    _inherit = 'crm.lead'

    reveal_ip = fields.Char(string='IP Address')
    generated_by_reveal = fields.Boolean(string="Generated By Reveal", default=False)
